const ORDER_MODAL_OPEN = 'ORDER_MODAL_OPEN';
const INGREDIENT_MODAL_OPEN = 'INGREDIENT_MODAL_OPEN';
const MODAL_CLOSE = 'MODAL_CLOSE';


export {
    ORDER_MODAL_OPEN,
    INGREDIENT_MODAL_OPEN,
    MODAL_CLOSE
}